### ISSUE TITLE
Wrong File

### ISSUE THREAD

**Issue by PositivePeriod** [KSA-Research-Database/ksared-2020-docs#1]
https://research.ksa.hs.kr/2019GRD_CS13
파일 다운하면 다른 연구 파일이 올라가있습니다
bug report 기능이 있으면 좋겠습니다

**Comment by sni-J** [comment]
내용상의 오류는 교무연구부에 문의해주세요.
bug report는 현재 따로 구현 계획이 없으며 critical issue에 한해 교무연구부를 통해 전달해주시면 수정 및 반영하도록 하겠습니다.
